### ISSUE TITLE
GEOL_RNQ ABBR 

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#21]
remove: interbedded
add: vesicular

**Comment by digitalgeotechnics** [comment]
Agree.  
`interbedded` can be removed because there are other, arguably more consistent, provisions for characterising "interbedded" scenarios.

`vesicular` is useful to add, as in "VESICULAR BASALT", though presumably this would be a "nice to know addidition to the rock name and wouldn't replace the need to mention the presence of vesicles as a "feature" as per AS1726-2017 6.2.3.5(a)

**Comment by digitalgeotechnics** [comment]
Table 15 of AS1726-2017 also includes:
from Note 12:
`limonitic`
`zeolite`

from Note 13 - "the depositional origin of the sediment may be indicated by prefixes such as:
`aeolian`
`glacial`
`marine`

**Comment by digitalgeotechnics** [comment]
See also related #25

**Comment by SolidRockProgrammer** [comment]
Added these in excel 1.2

- aeolian
- glacial
- limonitic
- marine
- vesicular
- zeolite

**Comment by SolidRockProgrammer** [comment]
interbedded - removed
