### ISSUE TITLE
Is LTCH_SDEN needed if we have LTCH_BDEN?

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#3]

**Comment by SolidRockProgrammer** [comment]
There are two groups: LTCH and LTCT, i wonder if a third table is needed to model the general, stage and readings

**Comment by StephenDurham** [comment]
I should have given this group more thought, it really needs to be like those that have a group and a test as with this method there is a dry back curve and the density changes with decreasing moisture content, which is why I suggested the SDEN and indeed you are correct this should be in the LTCT group.

**Comment by StephenDurham** [comment]
We could even call it LTCT_BDEN

**Comment by SolidRockProgrammer** [comment]
@StephenDurham pls apply the changes you need in the 1.2 excel file, and mark the change log column

**Comment by SolidRockProgrammer** [comment]
created LTCT_BDEN and deleted LTCH_SDEN
