### ISSUE TITLE
ABBR for SOLM_MC

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#30]
v1.0 has
SOLM_MC, 	D , 		Dry
SOLM_MC, 	M , 		Moist
SOLM_MC, 	W , 		Wet
SOLM_MC, 	w < PL , 	Moist, dry of plastic limit
SOLM_MC, 	w = LL , 	**Moist**, near liquid limit
SOLM_MC, 	w = PL , 	Moist, near plastic limit
SOLM_MC, 	w > LL , 	**Moist**, wet of liquid limit
SOLM_MC, 	w > PL , 	Moist, wet of plastic limit

two rows have **moist** when it should be **wet**

I prefer to change these to
SOLM_MC, 	D		, 	Dry
SOLM_MC, 	M		, 	Moist
SOLM_MC, 	W		, 	Wet
SOLM_MC, 	M (w < PL)	, 	Moist, dry of plastic limit
SOLM_MC, 	W (w = LL)	, 	Wet, near liquid limit
SOLM_MC, 	M (w = PL)	, 	Moist, near plastic limit
SOLM_MC, 	W (w > LL)	, 	Wet, wet of liquid limit
SOLM_MC, 	M (w > PL) ,  	Moist, wet of plastic limit

**Comment by digitalgeotechnics** [comment]
@SolidRockProgrammer seems a sensible correction to the description.  

While we're on the topic it's worth noting that AS1726 6.1.7(a)(A) to (E) has "or" in each line, eg:

> 'Moist, near plastic limit'... (or 'w=PL')`

This suggests the ABBR codes could be simplified to the latter abbreviation ("w=PL" only) and the leading "M" or "W" and brackets are not necessary.  This makes sense to me because the M or W feel like redundant repetition as this state is implied be the reference to the plastic/liquid limits - kinda like when people say the weather is "rainy and wet"... Also, entry of the existing codes is more time consuming in databases/collector apps where the ABBR codes are used for the lookup,  as 6 or 8 key strokes are required before the term can be auto completed

**Comment by SThorin** [comment]
Thanks - I agree that we don't need the M or W before the brackets nor the brackets

**Comment by SolidRockProgrammer** [comment]
I agree it is redundant info for the well educated, but for the layman, they don't know what "w > LL" means

**Comment by SThorin** [comment]
This is why people who have not been trained to AS1726 should not log and especially not relative to plasticity limits - likely they would use the D, M, W only! Regarding the w>LL etc..there still is the description which has "Wet, wet of liquid limit" which covers this sufficiently IMO

**Comment by SolidRockProgrammer** [comment]
I am referring to data receivers and laymen who read printed logs

**Comment by SThorin** [comment]
I see....because well explained in the standard, and currently how we do it, i suggest we delete but happy either way

**Comment by SolidRockProgrammer** [comment]
I've been thinking alot about this
* alot of geotch companies use "w < PL" only etc
* we should remove the space, so "w<PL"

**Comment by digitalgeotechnics** [comment]
Indeed and agree. I hateredundantwhitespace.  I get the line of thinking re terms for laymen, but laypersons won’t likely be reading the AGS data (noting the term/code/abbreviation on the pdf log doesn’t have to be the same abbr code as in the ags). Looking at some of the abbr codes from other tables, use of terms that aren’t layperson friendly isn’t unprecedented is it?

**Comment by SolidRockProgrammer** [comment]
applied in 1.2
