### ISSUE TITLE
More defect types and infill material ABBR

### ISSUE THREAD

**Issue by SolidRockProgrammer** [australiangeomechanics/agsformat#31]
Cara at SMEC proposes

Defect Types

- CZ - Crushed Zone
- FZ - Fracture Zone
- XS - Extremely Weathered Seam
- FT - Fault
- VE - Vein
- VG - Vugh
- VO - Void

What of structures?

- Bedding BD A layered arrangement of minerals parallel to the surface of deposition which has caused planar anisotropy in the rock
- substance.
- Cleavage CV An alignment of fine grained minerals caused by deformation.
- Schistosity SH A layered arrangement of minerals to each other
- Foliation FO A planar alignment of minerals caused by deformation.
- Void VO A completely empty space
- Dyke DK Sheet-like bodies of igneous rock that cut across sedimentary bedding or foliations in rocks. They may be single or multiple in nature
- Sill SL A sill is an intrusion of magma that spreads underground between the layers of another kind of rock
- Contact CX A contact between intrusive and stratigraphic units.
- Boundary BN A distinct boundary between two stratigraphic units

Infill
- AM Azurite / Malachite 
- Ap Apatite
- Co Coal
- Ch Chlorite
- Cl Clay
- Cp Chalcopyrite
- Cy Chalcedony
- Ep Epidote
- Fe Limonite/Goethite
- FeO Iron oxide
- Fs Feldspar (K)
- FsC Feldspar (Ca/Na)
- Ga Galena
- Gp Gypsum
- He Hematite
- Is Ironstone
- Mn Manganese
- Pl Pyrolusite
- Py Pyrite
- Sd Siderite
- Se Serpentine minerals
- Sp Sphalerite
- Um Unidentified mineral
- X Carbonaceous
- Ze Zeolite

**Comment by SThorin** [comment]
Hi Phil,

Probably best to discuss in a meeting. These are usually rigorous geological terms but usually already catered for in AS1726 IMO.

Quick response below


  *   Defect types: Would generally reject the proposed defects. A void is an open defect, and best defined in the units. A fracture zone is pre-AS1726 2017 should not be used for current and future projects. As per AS1726, a fault should be distinguished between sheared surfaces, sheared sems and crushed seams as these behave differently engineering wise. Vugh --> Vug. I believe the intent in AS1726 is that a vein of rock material is described as a unit rather than as a defect (=no or little tensile strength).

  *   Infill: no issues, except Fe Fe Limonite/Goethite which I believe is only oxides of Fe3+ and does not allow for Fe2+ = would therefore have Fe for all iron oxides
  *   Structure: We already have a list in AS1726. Dyke and sills are effectively veins with a different orientation. A contact or boundary would fall in parting or joint.

Regards
S

From: Phil Wade ***@***.***>
Sent: Sunday, 2 January 2022 10:55 AM
To: australiangeomechanics/agsformat ***@***.***>
Cc: Assign ***@***.***>
Subject: [australiangeomechanics/agsformat] More defect types and infill material ABBR (Issue #31)


CAUTION: This email is sent from an external source. Do not click any links or open attachments unless you recognise the sender and know the content is safe.



Cara at SMEC proposes

Defect Types

  *   CZ - Crushed Zone
  *   FZ - Fracture Zone
  *   XS - Extremely Weathered Seam
  *   FT - Fault
  *   VE - Vein
  *   VG - Vugh
  *   VO - Void

What of structures?

  *   Bedding BD A layered arrangement of minerals parallel to the surface of deposition which has caused planar anisotropy in the rock
  *   substance.
  *   Cleavage CV An alignment of fine grained minerals caused by deformation.
  *   Schistosity SH A layered arrangement of minerals to each other
  *   Foliation FO A planar alignment of minerals caused by deformation.
  *   Void VO A completely empty space
  *   Dyke DK Sheet-like bodies of igneous rock that cut across sedimentary bedding or foliations in rocks. They may be single or multiple in nature
  *   Sill SL A sill is an intrusion of magma that spreads underground between the layers of another kind of rock
  *   Contact CX A contact between intrusive and stratigraphic units.
  *   Boundary BN A distinct boundary between two stratigraphic units

Infill

  *   AM Azurite / Malachite
  *   Ap Apatite
  *   Co Coal
  *   Ch Chlorite
  *   Cl Clay
  *   Cp Chalcopyrite
  *   Cy Chalcedony
  *   Ep Epidote
  *   Fe Limonite/Goethite
  *   FeO Iron oxide
  *   Fs Feldspar (K)
  *   FsC Feldspar (Ca/Na)
  *   Ga Galena
  *   Gp Gypsum
  *   He Hematite
  *   Is Ironstone
  *   Mn Manganese
  *   Pl Pyrolusite
  *   Py Pyrite
  *   Sd Siderite
  *   Se Serpentine minerals
  *   Sp Sphalerite
  *   Um Unidentified mineral
  *   X Carbonaceous
  *   Ze Zeolite

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3Pi8q5NGPKHTzQYYRJbYLN97VN?u=https%3A%2F%2Fgithub.com%2Faustraliangeomechanics%2Fagsformat%2Fissues%2F31>, or unsubscribe<https://clicktime.symantec.com/3KXPd4pe1d6iyj9AhuxQVrc7VN?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAGUCSHZPEV72IDFHYVOD3UT6H7BANCNFSM5LC76XMQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://clicktime.symantec.com/35xUekAsqWpPymsCtyrx5gS7VN?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://clicktime.symantec.com/3QLrXi1UVNzrSZo4G6XB8417VN?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.
You are receiving this because you were assigned.Message ID: ***@***.******@***.***>>

This email is intended only for the addressee and may contain confidential information. If you receive this email in error please delete it and any attachments and notify the sender immediately by reply email. Transport for NSW takes all care to ensure that attachments are free from viruses or other defects. Transport for NSW assume no liability for any loss, damage or other consequences which may arise from opening or using an attachment.

P Consider the environment. Please don't print this e-mail unless really necessary.


OFFICIAL

**Comment by SolidRockProgrammer** [comment]
DISC_INFM is a X type, should not have abbr
For DISC_TYPE and other ABBR lists users can create custom ABBR records as needed if existing do not suffice.  We can accept suggestion in future for additional standard ABBR items.
